name: Remote cache experiment

on:
  workflow_dispatch:
  push:

jobs:
  remote-cache-experiment-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./remote-cache-experiment.sh
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

  remote-cache-experiment-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cache: ['transforms', 'kotlin-dsl', 'groovy-dsl']
        buildCache: ['build-cache', 'no-build-cache']
    steps:
    - uses: actions/checkout@v4
    - uses: gradle/actions/setup-gradle@v3
      with:
        cache-read-only: false
    - name: Run remote cache experiment
      run: |
        cache='${{ matrix.cache }}'
        buildCache='${{ matrix.buildCache }}'
        
        echo "Test caches/*/$cache removal with --$buildCache"

        # Run build once to fully populate Gradle User Home
        ./gradlew --no-daemon --no-configuration-cache -Ddevelocity.deprecation.muteWarnings=true help
        ./gradlew --no-daemon --no-configuration-cache -Ddevelocity.deprecation.muteWarnings=true -Dscan.uploadInBackground=false help        killall -9 java

        echo "Removing $cache from $homeDir/caches"
        rm -rf ~/.gradle/caches/*/$cache
        rm -rf ~/.gradle/caches/$cache-* # Also remove the transforms for Gradle 8.7

        # Always remove the local build cache, since we are testing connection with remote build cache
        rm -rf ~/.gradle/caches/build-cache-1

        ./gradlew -Dscan.tag.remote-cache-experiment-$cache-$buildCache --$buildCache --no-configuration-cache -Ddevelocity.deprecation.muteWarnings=true -Dscan.uploadInBackground=false help
      env:
        DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
        
      





    